# Generated by Django 3.2.15 on 2022-08-27 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(max_length=255, verbose_name="Заголовок_новостей"),
                ),
                ("datetime", models.DateTimeField(verbose_name="Дата&Время_новостей")),
                (
                    "tags",
                    models.CharField(
                        default="Yandex", max_length=50, verbose_name="Теги_новостей"
                    ),
                ),
            ],
        ),
    ]
